0x000000:
    call (draw_set_color[]:int32 (var 16777215))
    call (draw_text[]:int32 (var "INSTRUCTIONS ROOM.# #YOU WILL ENCOUNTER A SERIES OF ATTACK.# #PRESS [Z] TO FIRE THE WEAPON.# #YOU CAN TEST WEAPON HERE.#SPECIAL RULE:#BLUE LASERS WILL NOT HURT YOU IF YOU ARE STANDING STILL.##PRESS [SPACEBAR] TO CONTINUE.") (var 100s) (var 100s))
0x000040:
    exit
